fragment MetricAnswerFields on MetricAnswer {
  question {
    id
  }
  option {
    id
    score
  }
  submittedAt
}

fragment TechnologyFields on TechnologySurvey {
  id
  name
  imageId
  status
  description {
    id
    longText
    shortText
    longTextHtml
    shortTextHtml
  }
  viewerAnswers {
    ...MetricAnswerFields
  }
}

fragment SurveyInfoFields on Survey {
  id
  name
  authPageImageId
  authPageText
  slug
  description
  imageId
  workgroupImageId
  darkLabelsOnImageEnabled
  labelsOnImageEnabled
  workgroupName
  metricPageText
  emailLoginTitleText
}

fragment MetricFields on Metric {
  id
  name
  description
  pollModel
  scoreRange {
    min
    max
  }
  calculationMethod
  resultLabels {
    label
    description
    score
  }
  questions {
    id
    label
    description
    options {
      id
      label
      description
      score
    }
  }
  resultLabels {
    label
    description
    score
  }
}

fragment SurveyParticipantFields on Survey {
  technologies {
    ...TechnologyFields
  }
}

fragment SurveyCommonFields on Survey {
  ...SurveyInfoFields
  metrics {
    ...MetricFields
  }

  questionsCount
  technologiesCount

  project {
    id
    name
    summary
    description
    imageId
  }

  board {
    id
  }
}

fragment SurveyAllFields on Survey {
  ...SurveyCommonFields
  ...SurveyParticipantFields
}

fragment UserFields on User {
  id
  display
  roles
  isAdmin
}

query GetSurveyInfo($id: String!) {
  survey(id: $id) {
    ...SurveyInfoFields
  }
}

query GetSurveyFormInfo($id: String!) {
  survey(id: $id) {
    ...SurveyInfoFields
    board {
      id
    }
    project {
      id
    }
  }
}

query GetSurveyForAdmin($id: String!) {
  survey(id: $id) {
    ...SurveyCommonFields
  }
}

query GetSurvey($id: String!) {
  survey(id: $id) {
    ...SurveyAllFields
  }
  viewer {
    ...UserFields
  }
}

query GetMetricById($id: String!) {
  metric(id: $id) {
    ...MetricFields
  }
}

query GetAllSurveys {
  surveys {
    ...SurveyCommonFields
  }
}

query GetAllMetrics {
  metrics {
    ...MetricFields
  }
}

query Viewer {
  viewer {
    ...UserFields
  }
}

mutation SubmitSurveyAnswer($input: SubmitSurveyAnswerInput!) {
  submitAnswer(input: $input) {
    ...MetricAnswerFields
  }
}

mutation UpdateSurvey($input: UpdateSurveyInput!) {
  updateSurvey(input: $input) {
    ...SurveyInfoFields
  }
}

mutation CreateMetric($input: CreateMetricInput!) {
  createMetric(input: $input) {
    ...MetricFields
  }
}

mutation CreateSurvey($input: CreateSurveyInput!) {
  createSurvey(input: $input) {
    ...SurveyCommonFields
  }
}

mutation UpdateMetric($input: UpdateMetricInput!) {
  updateMetric(input: $input) {
    ...MetricFields
  }
}

mutation resetSurveyAnswers($surveyId: String!) {
  resetSurveyAnswers(surveyId: $surveyId)
}

mutation Logout {
  logout
}
