fragment LoginSuccessFields on LoginWithPasswordSuccess {
  token
  viewer {
    id
    display
    roles
    isAdmin
  }
}

mutation Login($email: String!, $password: String!) {
  loginWithPassword(email: $email, password: $password) {
    ...LoginSuccessFields
  }
}

mutation Logout {
  logout
}

fragment TechnologyFields on Technology {
  id
  name
  status
  imageId
}

query GetTechnologies {
  technologies {
    ...TechnologyFields
  }
}

fragment SurveyFields on Survey {
  id
  name
}

query GetSurveys {
  surveys {
    ...SurveyFields
  }
}